namespace:
  name: staging

containerPort: 3111

service:
  port: 5111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: dhubrk/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits:
    cpu: 500m
    memory: 128Mi

livenessProbe:
    path: /healthz
    port: 3111
  
readinessProbe:
    path: /healthz
    port: 3111

