namespace:
  name: sandbox

containerPort: 3111

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: dhubrk/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

livenessProbe:
    path: /healthz
    port: 3111
  
readinessProbe:
    path: /healthz
    port: 3111

